export const modal_style = {
    position: 'absolute' as 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    outline: 'none',
    bgcolor: 'background.paper',
    border: '2px solid rgba(255, 255, 255, 0.2)',
    boxShadow: 24,
    p: 4,
    borderRadius: '16px'
  }
  
  export const intrinsicParameters = [
    'phase',
    'total_mass',
    'mass_1',
    'mass_2',
    'symmetric_mass_ratio',
    'spin_1x',
    'spin_1y',
    'spin_1z',
    'spin_2x',
    'spin_2y',
    'spin_2z',
    'phi_1',
    'phi_2',
    'chi_eff',
    'chi_1_in_plane',
    'chi_2_in_plane',
    'chi_p',
    'cos_tilt_1',
    'cos_tilt_2',
    'mass_1_source',
    'mass_2_source',
    'chirp_mass_source',
    'total_mass_source'
  ]
  export const extrinsicParameters = [
    'azimuth',
    'zenith',
    'H1_time',
    'luminosity_distance',
    'geocent_time',
    'dec',
    'ra',
    'iota',
    'redshift',
    'comoving_distance'
  ]
  export const miscellaneousParameters = [
    'chirp_mass',
    'mass_ratio',
    'a_1',
    'a_2',
    'tilt_1',
    'tilt_2',
    'phi_12',
    'phi_jl',
    'theta_jn',
    'psi',
    'recalib_H1_amplitude_0',
    'recalib_H1_amplitude_1',
    'recalib_H1_amplitude_2',
    'recalib_H1_amplitude_3',
    'recalib_H1_amplitude_4',
    'recalib_H1_amplitude_5',
    'recalib_H1_amplitude_6',
    'recalib_H1_amplitude_7',
    'recalib_H1_amplitude_8',
    'recalib_H1_amplitude_9',
    'recalib_H1_phase_0',
    'recalib_H1_phase_1',
    'recalib_H1_phase_2',
    'recalib_H1_phase_3',
    'recalib_H1_phase_4',
    'recalib_H1_phase_5',
    'recalib_H1_phase_6',
    'recalib_H1_phase_7',
    'recalib_H1_phase_8',
    'recalib_H1_phase_9',
    'recalib_L1_amplitude_0',
    'recalib_L1_amplitude_1',
    'recalib_L1_amplitude_2',
    'recalib_L1_amplitude_3',
    'recalib_L1_amplitude_4',
    'recalib_L1_amplitude_5',
    'recalib_L1_amplitude_6',
    'recalib_L1_amplitude_7',
    'recalib_L1_amplitude_8',
    'recalib_L1_amplitude_9',
    'recalib_L1_phase_0',
    'recalib_L1_phase_1',
    'recalib_L1_phase_2',
    'recalib_L1_phase_3',
    'recalib_L1_phase_4',
    'recalib_L1_phase_5',
    'recalib_L1_phase_6',
    'recalib_L1_phase_7',
    'recalib_L1_phase_8',
    'recalib_L1_phase_9',
    'recalib_H1_frequency_0',
    'recalib_H1_frequency_1',
    'recalib_H1_frequency_2',
    'recalib_H1_frequency_3',
    'recalib_H1_frequency_4',
    'recalib_H1_frequency_5',
    'recalib_H1_frequency_6',
    'recalib_H1_frequency_7',
    'recalib_H1_frequency_8',
    'recalib_H1_frequency_9',
    'recalib_L1_frequency_0',
    'recalib_L1_frequency_1',
    'recalib_L1_frequency_2',
    'recalib_L1_frequency_3',
    'recalib_L1_frequency_4',
    'recalib_L1_frequency_5',
    'recalib_L1_frequency_6',
    'recalib_L1_frequency_7',
    'recalib_L1_frequency_8',
    'recalib_L1_frequency_9',
    'log_likelihood',
    'log_prior',
    'reference_frequency',
    'waveform_approximant',
    'minimum_frequency',
    'H1_matched_filter_snr',
    'H1_optimal_snr',
    'L1_matched_filter_snr',
    'L1_optimal_snr'
  ]

  export const otherParameters = [
    'All other parameters not defined under Intrinsic, Extrinsic, or Miscellaneous'
  ]